apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: apache-airflow-containerized
  name: apache-airflow-containerized
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: apache-airflow-containerized
  type: NodePort
status:
  loadBalancer: {}
