apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: apache-airflow-mysql
  name: apache-airflow-mysql
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: apache-airflow-mysql
  type: NodePort
status:
  loadBalancer: {}
